spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/urlshortener}
spring.datasource.username=${DB_USERNAME:urlshortener}
spring.datasource.password=${DB_PASSWORD:urlshortener}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.base-url=${APP_BASE_URL:http://localhost:8080}
app.instance-name=${INSTANCE_NAME:local-instance}

server.forward-headers-strategy=framework

app.cache.enabled=false
