spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/urlshortener}
spring.datasource.username=${DB_USERNAME:urlshortener}
spring.datasource.password=${DB_PASSWORD:urlshortener}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.base-url=${APP_BASE_URL:http://localhost:8080}
app.instance-name=${INSTANCE_NAME:local-instance}

server.forward-headers-strategy=framework

app.cache.enabled=true
app.cache.redirect-ttl=PT1H

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.connect-timeout=500ms
spring.data.redis.timeout=500ms
